name: AxTrade
version: '${project.version}'
main: com.artillexstudios.axtrade.AxTrade
api-version: '1.20'
folia-supported: true

permissions:
  axtrade.admin:
    default: op
  axtrade.trade:
    default: true
  axtrade.toggle:
    default: true

softdepend:
  - AxQuestBoard
  - PlaceholderAPI
  - PlayerPoints
  - TokenManager
  - RivalHarvesterHoes
  - RoyaleEconomy
  - SuperMobCoins
  - TheOnly-MobCoins
  - UltraEconomy
  - RedisEconomy
  - BeastTokens
  - EcoBits
  - RivalCredits
  - AxShulkers
