name: Build Plugin

on:
  push:
    branches: [ main, master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean package
      
    - name: Extract version from pom.xml
      id: version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Plugin version: $VERSION"
      
    - name: Rename JAR with version and commit hash
      run: |
        COMMIT_HASH=${GITHUB_SHA:0:7}
        VERSION=${{ steps.version.outputs.version }}
        mv target/AxTrade-*.jar target/AxTrade-${VERSION}-${COMMIT_HASH}.jar
        echo "Final JAR name: AxTrade-${VERSION}-${COMMIT_HASH}.jar"
      
    - name: Upload final JAR
      uses: actions/upload-artifact@v4
      with:
        name: AxTrade-plugin
        path: target/AxTrade-*-*.jar
        retention-days: 90
